config/routes.rb
Rails.application.routes.draw do
  resources :images, only: [:create, :destroy]

  devise_for :users, path: '', controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'users/registrations' }
  resources :adverts do
    member do
      get 'change_state'
      #get 'in_moderate'
      #get 'in_archive'
      #get 'in_newest'
    end
  end

  root 'home#index'

  devise_for :admins, path: 'admin', controllers: { sessions: 'admin/sessions' }, skip: [:registrations]
  as :admin do
    get 'admin/edit' => 'admin/registrations#edit', :as => 'edit_admin_registration'
    put 'admin/' => 'admin/registrations#update', :as => 'admin_registration'
  end
  namespace :admin do
    root 'adverts#index'
    resources :categories, only: [:index, :new, :edit, :create, :update]
    resources :adverts, only: [:index, :show] do
      resources :logs, only: [:new, :create]
      member do
        get 'in_publish'
      end
    end
    resources :users do
      member do
        get 'user_adverts_with_state'
      end
    end
  end
end

app/views/layouts/admin/_navbar.html.slim
div class="navbar navbar-default navbar-fixed-top" role="navigation"
  div class="navbar-header"
    button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-inverse-collapse"
      span class="icon-bar"
      span class="icon-bar"
      span class="icon-bar"
    = link_to "Admin panel", admin_root_path, class:"navbar-brand"
  div class="navbar-collapse collapse navbar-inverse-collapse"
    ul class="nav navbar-nav"
      = content_tag :li, class: ("active" if params[:controller] == "admin/adverts") do
        = link_to "Adverts", admin_adverts_path
      = content_tag :li, class: ("active" if params[:controller] == "admin/users") do
        = link_to "Users", admin_users_path
      = content_tag :li, class: ("active" if params[:controller] == "admin/categories") do
        = link_to "Categories", admin_categories_path
    ul class="nav navbar-nav pull-right"
      = content_tag :li, class: ("active" if params[:controller] == "admin/registrations" && params[:action] == "edit") do
        = link_to "Edit profile", edit_admin_registration_path
      li = link_to "Sign out", destroy_admin_session_path, method: :delete

app/views/layouts/admin/admin.html.slim
doctype html
html
  head
    title Billboard
    = stylesheet_link_tag    'admin', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'admin', 'data-turbolinks-track' => true
    = csrf_meta_tags
  body

  = render 'layouts/admin/navbar'
  = render 'layouts/shared/flash'
  = yield

app/views/layouts/admin/devise.html.slim
doctype html
html
  head
    title Billboard
    = stylesheet_link_tag    'devise', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'devise', 'data-turbolinks-track' => true
    = csrf_meta_tags
  body
    div.container
      = render 'layouts/shared/flash'
      = yield