config/routes.rb
Rails.application.routes.draw do
  resources :images, only: [:create, :destroy]

  devise_for :users, path: '', controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'users/registrations' }
  resources :adverts do
    member do
      get 'change_state'
      #get 'in_moderate'
      #get 'in_archive'
      #get 'in_newest'
    end
  end

  root 'home#index'

  devise_for :admins, path: 'admin', controllers: { sessions: 'admin/sessions' }, skip: [:registrations]
  as :admin do
    get 'admin/edit' => 'admin/registrations#edit', :as => 'edit_admin_registration'
    put 'admin/' => 'admin/registrations#update', :as => 'admin_registration'
  end
  namespace :admin do
    root 'adverts#index'
    resources :categories, only: [:index, :new, :edit, :create, :update]
    resources :adverts, only: [:index, :show] do
      resources :logs, only: [:new, :create]
      member do
        get 'in_publish'
      end
    end
    resources :users do
      member do
        get 'user_adverts_with_state'
      end
    end
  end
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :adverts

  scope :recent, -> { order(created_at: :desc) }

  validates :name, presence: true, length: { maximum: 50 }
  validates :name, uniqueness: true
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::AdminController
  load_and_authorize_resource
  respond_to :json

  def index
    @categories = Category.recent.paginate(page: params[:page], per_page: 20)
  end

  def new
    form_html = string_form(@category)
    respond_with html: form_html
  end

  def edit
    form_html = string_form(@category)
    respond_with html: form_html
  end

  def create
    is_create = @category.save
    if is_create
      category_html = string_category(@category)
    else
      form_html = string_form(@category)
    end
    render json: { create_status: is_create, form_html: form_html, category_html: category_html }
  end

  def update
    is_create = @category.update(category_params)
    if is_create
      category_html = string_category(@category)
    else
      form_html = string_form(@category)
    end
    render json: { create_status: is_create, form_html: form_html, category_html: category_html, id: @category.id }
  end

  private
  def string_form(category)
    render_to_string(partial: 'admin/categories/form', formats: [:html], locals: { category: category })
  end

  def string_category(category)
    render_to_string(partial: 'admin/categories/category', formats: [:html], locals: { category: category })
  end

  def category_params
    params.require(:category).permit(:name)
  end
end

app/views/admin/categories/_category.html.slim
li class="list-group-item category-#{category.id}"
  span class="badge" = category.adverts_count
  = category.name
  p = link_to "Edit", edit_admin_category_path(category), class:"btn btn-primary btn-xs get_modal", remote: true

app/views/admin/categories/_form.html.slim
div class="modal" id="categoryModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true"
  div class="modal-dialog"
    div class="modal-content"
      div class="modal-header"
        button type="button" class="close" data-dismiss="modal"
          span aria-hidden="true"
            | &times;
            span class="sr-only" Close
        h4 class="modal-title" id="myModalLabel" Show advert full info
      div class="modal-body"
        = simple_form_for [:admin, category], remote: true, "data-type" => "json" do |f|
          = f.error_notification
          = f.input :name, autofocus: true, input_html: { maxlength: 50 }
          div class="modal-footer"
            = f.submit class:"btn btn-success"

app/views/admin/categories/index.html.slim
div class="container col-md-3 col-md-offset-4"
  h3 Categories
  p = link_to "New category", new_admin_category_path, class:"btn btn-default btn-sm get_modal", remote: true
  ul class="list-group categories_wrapper"
    = render @categories
  = will_paginate @categories, renderer: BootstrapPagination::Rails