config/routes.rb
Rails.application.routes.draw do
  resources :images, only: [:create, :destroy]

  devise_for :users, path: '', controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'users/registrations' }
  resources :adverts do
    member do
      get 'change_state'
      #get 'in_moderate'
      #get 'in_archive'
      #get 'in_newest'
    end
  end

  root 'home#index'

  devise_for :admins, path: 'admin', controllers: { sessions: 'admin/sessions' }, skip: [:registrations]
  as :admin do
    get 'admin/edit' => 'admin/registrations#edit', :as => 'edit_admin_registration'
    put 'admin/' => 'admin/registrations#update', :as => 'admin_registration'
  end
  namespace :admin do
    root 'adverts#index'
    resources :categories, only: [:index, :new, :edit, :create, :update]
    resources :adverts, only: [:index, :show] do
      resources :logs, only: [:new, :create]
      member do
        get 'in_publish'
      end
    end
    resources :users do
      member do
        get 'user_adverts_with_state'
      end
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  devise :omniauthable, omniauth_providers: [:facebook, :vkontakte, :twitter, :google_oauth2]
  has_many :adverts, dependent: :destroy

  class << self
    def find_for_social_oauth(auth)
      User.find_or_create_by(provider: auth.provider, uid: auth.uid) do |user|
        user.provider = auth.provider
        user.uid = auth.uid
        user.email = "#{auth.uid}@#{auth.provider}.com"
        user.password = Devise.friendly_token[0, 20]
      end
    end
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::AdminController
  load_and_authorize_resource
  respond_to :json

  def index
    @users = User.all.paginate(page: params[:page], per_page: 20)
  end

  def user_adverts_with_state
    @adverts = Advert.includes(:category, :type).where(user_id: params[:id], state: params[:state])
    adverts = render_to_string(partial: 'admin/users/user_adverts', formats: [:html], locals: { adverts: @adverts })
    respond_with html: adverts
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  providers = [:facebook, :vkontakte, :twitter, :google_oauth2]
  providers.each do |provider|
    define_method(provider.to_sym) do
      @user = User.find_for_social_oauth(request.env['omniauth.auth'])
      if @user.persisted?
        sign_in_and_redirect @user, event: :authentication
        set_flash_message(:notice, :success, kind: provider) if is_navigational_format?
      else
        session["devise.#{provider}_data"] = request.env['omniauth.auth']
        redirect_to new_user_session_path
      end
    end
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  def update
    account_update_params = devise_parameter_sanitizer.sanitize(:account_update)

    if account_update_params[:password].blank?
      account_update_params.delete('password')
      account_update_params.delete('password_confirmation')
    end

    @user = User.find(current_user.id)
    if @user.update_attributes(account_update_params)
      set_flash_message :notice, :updated
      sign_in @user, bypass: true
      redirect_to after_update_path_for(@user)
    else
      render 'edit'
    end
  end
end

app/views/admin/users/_user.html.slim
tr class="warning user-#{user.id}"
    td = user.email
    td = user.last_sign_in_at
    - %w(moderated rejected published).each do |state|
      td = link_to "#{state.capitalize}", user_adverts_with_state_admin_user_path(id: user.id, state: "#{state}"), remote: true, "data-type" => "json", class:"user_adverts get_modal"

app/views/admin/users/_user_adverts.html.slim
div class="modal" id="advertModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true"
  div class="modal-dialog modal-lg"
    div class="modal-content"
      div class="modal-header"
        button type="button" class="close" data-dismiss="modal"
          span aria-hidden="true"
            | &times;
            span class="sr-only" Close
        h4 class="modal-title" id="myModalLabel" Show adverts
      div class="modal-body"
        table class="table table-hover"
          thead
            tr
              th Title
              th Description
              th Price 
              th Category
              th Type
              th Posted by
              th
              th
          = render adverts

app/views/admin/users/index.html.slim
div class="user_adverts_wrapper"
h2 Users
table class="table table-hover"
  thead
    tr
      th Email
      th Last sign in
      th
      th
      th
  = render @users
= will_paginate @users, renderer: BootstrapPagination::Rails